name: Build ASP.NET App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore Sprint/Sprint.sln

      - name: Build app
        run: dotnet build Sprint/Sprint.sln --configuration Release --no-restore

      - name: Publish app
        run: dotnet publish Sprint/Sprint.sln --configuration Release --output ./publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: aspnet-app
          path: ./publish